ersion: '3.8'
services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf
    restart: always
    environment:
     - http_proxy=
     - https_proxy=
     - MOBSF_API_KEY=360be513eb4af9bd652cf14cda6f30be909c40db4de448a7e3cd3b5f1d6a65ee
    ports:
     - 8000:8000
  nginx_mobsf:
    restart: always
    image: rp4mobsf
    ports:
      - 80:80
      - 443:443
    environment:
      DH_SIZE: 512
      FORWARD_HOST:
      FORWARD_PORT: 8000
    volumes:
      - /opt/MobSF/RP4MobSF/conf/conf.d/:/etc/nginx/conf.d
      - /opt/MobSF/RP4MobSF/conf/pki/:/etc/nginx/pki
      - /opt/MobSF/RP4MobSF/conf/auth/:/etc/nginx/auth
